# Generated by Django 6.0.5 on 2026-06-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_saleinvoice_saleinvoiceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importreceipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_import_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hiệu lực'), ('CANCELLED', 'Đã hủy')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sale_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hiệu lực'), ('CANCELLED', 'Đã hủy')], default='ACTIVE', max_length=20),
        ),
    ]
